rush01_Nginx/ex/urls.py
from django.shortcuts import redirect
from django.urls import path
from .views import views
from django.conf.urls.static import static
from .views.views import Register, Show_Page
from rush01 import settings

urlpatterns = [
    path("index/", views.Index.as_view(), name="index"),
    path("register/", views.Register.as_view(), name="register"),
    path("", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("tip/", views.Tip.as_view(), name="tip"),
    path("profile/", views.Profile_Edit, name="profile"),
    path("admin/", views.Admin_edit, name="admin"),
    path("articles/", views.ArticleView.as_view(), name="article"),
    # path("detail/<pk>", views.Detail_View.as_view(), name="detail"),
    path("detail/<pk>", views.article_detail, name="detail"),
    path("publicate/", views.PublicView.as_view(), name="publication"),
    path("publish/", views.Publish.as_view(), name="publish"),
    path(
        "create_comment/<int:commnets_id>",
        views.Create_comment.as_view(),
        name="create_comment",
    ),
    path(
        "create_recomment/<int:commnets_id>", views.Create_recomment, name="create_recomment"
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rush01_Nginx/rush01/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ex.urls'))
]

rush01_Nginx/ex/models.py
from django.contrib import auth
from django.contrib.auth.models import User
from django.db import models
from django.db.models.expressions import Expression
from django.db.models.query_utils import select_related_descend
from django.db.utils import DatabaseError


class UpVoteModel(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now_add=True,
    )


class DownVoteModel(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now_add=True,
    )


class TipModel(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.TextField(null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    date = models.DateTimeField(auto_now_add=True)
    up_votes = models.ManyToManyField(UpVoteModel)
    down_votes = models.ManyToManyField(DownVoteModel)
    updated_at = models.DateTimeField(auto_now=True)

    def upvote(self, user):
        try:
            down_vote: DownVoteModel = self.down_votes.get(author=user)
            down_vote.delete()
        except DownVoteModel.DoesNotExist as e:
            pass
        try:
            up_vote: UpVoteModel = self.up_votes.get(author=user)
            up_vote.delete()
        except UpVoteModel.DoesNotExist as e:
            up_vote = UpVoteModel(author=user)
            up_vote.save()
            self.up_votes.add(up_vote)
            self.save()

    def downvote(self, user):
        try:
            up_votes: UpVoteModel = self.up_votes.get(author=user)
            up_votes.delete()
        except UpVoteModel.DoesNotExist as e:
            pass
        try:
            down_vote: DownVoteModel = self.down_votes.get(author=user)
            down_vote.delete()
        except DownVoteModel.DoesNotExist as e:
            down_vote = DownVoteModel(author=user)
            down_vote.save()
            self.down_votes.add(down_vote)
            self.save()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    # User모델과 Profile을 1:1로 연결
    description = models.TextField(blank=True)
    nickname = models.CharField(max_length=40, blank=True)
    image = models.ImageField(blank=True)
    # email =
    # first_name =
    # last_name =


class Article(models.Model):
    title = models.CharField(max_length=64, null=False)
    author = models.ForeignKey(
        User, related_name="article", on_delete=models.CASCADE, null=True
    )
    created = models.DateTimeField(auto_now_add=True)
    # synopsis = models.CharField(max_length=312, null=False)
    content = models.TextField(null=False)

    # 내림차순
    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return str(self.title)


class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE)
    body = models.CharField("reply", max_length=150)
    created_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User, related_name="Comment", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.body


class ReComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    body = models.CharField("Re_reply", max_length=150)
    created_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User, related_name="Recomment", on_delete=models.CASCADE, null=False
    )

    def __str__(self):
        return self.body

rush01_Nginx/ex/views/views.py
from typing import Any, Dict
from django.db.utils import DatabaseError
from django.http import request
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.views.generic import FormView, DetailView, ListView
from django.contrib.auth import login
from django.contrib import messages
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django import db
from django.shortcuts import render, get_object_or_404
from rush01 import settings
from django.conf.urls.static import static


from ex.forms.forms import (
    TipForm,
    DeleteTipForm,
    VoteForm,
    CustomUserChangeForm,
    ProfileForm,
    RegisterForm,
    PublishForm,
    CommentForm,
    ReCommentForm,
)
from ex.models import TipModel, Profile, Article, ReComment
from django.urls import reverse_lazy


class Index(View):
    template_name = "index.html"

    def get(self, request):
        try:
            tips = TipModel.objects.all().order_by("-date")

        except db.DatabaseError as e:
            tips = []
        context = {
            "tipform": TipForm(),
            "tips": [
                {
                    "id": tip.id,
                    "content": tip.content,
                    "author": tip.author,
                    "date": tip.date,
                    "up_votes": tip.up_votes,
                    "down_votes": tip.down_votes,
                    "deleteform": DeleteTipForm(tip.id),
                    "voteform": VoteForm(tip.id),
                }
                for tip in tips
            ],
        }
        print([(tip.up_votes.count(), tip.down_votes.count()) for tip in tips])
        return render(request, self.template_name, context)


class Logout(LoginRequiredMixin, View):
    login_url = reverse_lazy("login")

    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("login")


class Show_Page(View):
    template_name = "mainpage.html"

    def get(self, request):
        context = {}
        return render(request, self.template_name, context)


class Register(FormView):
    template_name = "register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("publication")

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if self.request.user.is_authenticated:
            messages.error(self.request, "You already logined!")
            return redirect("publication")
        return super().get(request, *args, **kwargs)

    def form_valid(self, form: RegisterForm):
        user = form.save()
        login(self.request, user)
        messages.success(self.request, "Registration successful.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Unsuccessful registration. Invalid information.")
        return super().form_invalid(form)


class Login(FormView):
    template_name = "login.html"
    form_class = AuthenticationForm
    success_url = reverse_lazy("publication")

    # def get_initial(self) -> Dict[str, Any]:
    #     initial = super().get_initial()
    #     initial['username'] = self.request.username
    #     initial['first_name'] = self.request.first_name
    #     initial['last_name'] = self.request.last_name
    #     initial['email'] = self.request.id
    #     initial['content'] = self.request.content
    #     initial['author'] = self.request.author
    #     initial['image'] = self.request.image
    #     initial['nickname'] = self.request.nickname
    #     initial['description'] = self.request.description
    #     return initial

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if self.request.user.is_authenticated:
            messages.error(self.request, "You already logined!")
            return redirect("publication")
        return super().get(request, *args, **kwargs)

    def form_valid(self, form: AuthenticationForm):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is None:
            messages.error(self.request, "Invalid username or password.")
            return super().form_invalid(form)
        login(self.request, user)
        messages.info(self.request, f"You are now logged in as {username}.")
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


class Tip(LoginRequiredMixin, View):
    http_method_names = ["post", "put", "delete"]
    login_url = reverse_lazy("login")

    def dispatch(self, *args, **kwargs):
        method = self.request.POST.get("_method", "").lower()
        if method == "put":
            return self.put(*args, **kwargs)
        if method == "delete":
            return self.delete(*args, **kwargs)
        return super(Tip, self).dispatch(*args, **kwargs)

    def post(self, request):
        form = TipForm(request.POST)
        if form.is_valid():
            try:
                TipModel.objects.create(
                    content=form.cleaned_data["content"], author=self.request.user
                )
                messages.success(self.request, "Successful create Tip.")
            except DatabaseError as e:
                print(e)
                messages.error(self.request, "Unsuccessful create Tip. (db error)")
        else:
            messages.error(
                self.request, "Unsuccessful create Tip. (Invalid form data.)"
            )
        return redirect("publication")

    def __error_msg(self, method, msg):
        messages.error(self.request, f"Unsuccessful {method} Tip. ({msg})")
        return redirect("publication")

    def delete(self, request: HttpRequest):
        form = DeleteTipForm(None, request.POST)
        if not form.is_valid():
            return self.__error_msg("delete", "Invaild form data.")
        try:
            tip: TipModel = TipModel.objects.get(id=form.cleaned_data["id"])
            if (
                tip.author != request.user
                and request.user.is_staff == False
                and request.user.is_superuser == False
            ):
                return self.__error_msg("delete", "access denied")
            tip.delete()
            messages.success(self.request, "Successful Erase Tip.")
        except TipModel.DoesNotExist as e:
            return self.__error_msg("delete", "Tip does not exist")
        except DatabaseError as e:
            return self.__error_msg("delete", "db error")

        return redirect("publication")

    def put(self, request):
        form = VoteForm(None, request.POST)
        if not form.is_valid():
            return self.__error_msg("vote", "Invaild form data.")
        try:
            tip: TipModel = TipModel.objects.get(id=form.cleaned_data["id"])
            if form.cleaned_data["type"]:
                tip.upvote(request.user)
            elif (
                tip.author != request.user
                and request.user.groups.filter(name="NoNo").exists()
            ):
                return self.__error_msg("vote", "Oh... You are a NoNo User! No!!")
            else:
                tip.downvote(request.user)
        except TipModel.DoesNotExist as e:
            return self.__error_msg("vote", "Tip does not exist")
        except DatabaseError as e:
            return self.__error_msg("vote", "db error")
        messages.success(request, "Dood Voted!")
        return redirect("publication")


def Profile_Edit(request):
    if request.method == "POST":
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        profile_form = ProfileForm(
            "12345",
            "6789",
            "image_hahehihoho",
            request.POST,
            request.FILES,
            instance=request.user.profile,
        )
        if user_change_form.is_valid() and profile_form.is_valid():
            user = user_change_form.save()
            profile_form.save()
            return redirect("publication")
        return redirect("profile")
    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
        # 새롭게 추가하는 것이 아니라 수정하는 것이기 때문에
        # 기존의 정보를 가져오기 위해 instance를 지정해야 한다.
        profile, create = Profile.objects.get_or_create(user=request.user)
        # Profile 모델은 User 모델과 1:1 매칭이 되어있지만
        # User 모델에 새로운 인스턴스가 생성된다고 해서 그에 매칭되는 Profile 인스턴스가 생성되는 것은 아니기 때문에
        # 매칭되는 Profile 인스턴스가 있다면 그것을 가져오고, 아니면 새로 생성하도록 한다.
        profile_form = ProfileForm(
            "12345", "6789", "image_hahehihoho", instance=profile
        )
        return render(
            request,
            "profile.html",
            {"user_change_form": user_change_form, "profile_form": profile_form},
        )


class ArticleView(ListView):
    paginate_by = 10
    template_name = "post.html"
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)


# class Detail_View(DetailView):
#     template_name = "post_detail.html"
#     model = Article

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         print(context)
#         return context


def article_detail(request, pk):

    article = get_object_or_404(Article, pk=pk)

    # 만약 post일때만 댓글 입력에 관한 처리를 더한다.
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        comment_form.instance.author_id = request.user.id
        comment_form.instance.document_id = pk
        if comment_form.is_valid():
            comment = comment_form.save()

    # models.py에서 document의 related_name을 comments로 해놓았다.

    comment_form = CommentForm()

rush01_Nginx/ex/templates/base.html
{% load static %} {% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}Life Pro Tips</title>
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <style>
        background-image: url("https://blogfiles.pstatic.net/MjAyMTA2MDhfMTU5/MDAxNjIzMDgwMDY4ODkx.33N3hA4q2VW3FgV0mRLkq-w5-5_KcAlwLcsNyEz_Rr8g.eFB4D7xecNKAAXVx8RIbEsJ59N6rPCKvvLIx7gnk2bYg.JPEG.123gk/florian-olivo-4hbJ-eymZ1o-unsplash.jpg"); 
        height: 500px;
        width: 100%;
        background-repeat: no-repeat;
        background-position: center center;
        background-attachment: fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    </style>
    {% bootstrap_css %} {% bootstrap_javascript %}
  </head>
  <body>
    {% include 'nav.html' %}
    <div class="container">
      {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
      {% block content %}
      <h1>{{ request.path }}</h1>
      <span>Please replace content!</span>
      {% endblock content %}
    </div>
  </body>
</html>

rush01_Nginx/ex/templates/index.html
{% extends 'base.html' %} {% block content %} {% load bootstrap3 %}

<div>
  {% if user.is_authenticated %}
  <!-- Button trigger modal -->
  <button
    type="button"
    class="btn btn-primary"
    data-toggle="modal"
    data-target="#createtip"
  >
    Create Tip!
  </button>

  <!-- Modal -->
  <div
    class="modal fade"
    id="createtip"
    tabindex="-1"
    role="dialog"
    aria-labelledby="createtipLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header" style="display: flex; flex-direction: row">
          <h5
            class="modal-title inline"
            style="width: 100%"
            id="createtipLabel"
          >
            Create Tip!
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{% url 'tip' %}" method="post" class="form">
          <div class="modal-body">
            {% csrf_token %} {% bootstrap_form tipform %}
          </div>
          <div class="modal-footer">
            {% buttons %}
            <button type="submit" class="btn btn-primary">
              {% bootstrap_icon "star" %} Submit
            </button>
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              Close
            </button>
            {% endbuttons %}
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endif %}

  <ul class="list-group">
    {% for tip in tips %}
    <li class="list-group-item" style="margin-top: 10px; margin-bottom: 10px">
      {% if user.is_authenticated %}
      <form
        action="{% url 'tip' %}"
        method="post"
        class="form"
        style="display: none"
      >
        {% csrf_token %}
        <input type="hidden" name="_method" value="put" id="_method" />
        <input type="hidden" name="id" value="{{ tip.id }}" />
        <input type="checkbox" hidden="true" name="type" id="type" checked />
        <input
          hidden="true"
          type="submit"
          class="btn btn-primary"
          id="{{tip.id}}-upvote"
        />

        {% comment %} {% for c in commemts %}

        .click.
        .click.
        .click
        {% endfor%} {% endcomment %}

      </form>
      <form
        action="{% url 'tip' %}"
        method="post"
        class="form"
        style="display: none"
      >
        {% csrf_token %}
        <input type="hidden" name="_method" value="put" id="_method" />
        <input type="hidden" name="id" value="{{ tip.id }}" />
        <input type="checkbox" hidden="true" name="type" id="type" />
        <input
          hidden="true"
          type="submit"
          class="btn btn-primary"
          id="{{tip.id}}-downvote"
        />
      </form>
      {% endif %}
      <div>
        <h5>
          {% if user == tip.author or user.is_superuser or user.is_staff%}
          <button
            type="button"
            class="btn close"
            data-toggle="modal"
            data-target="#deletetip-{{ tip.id }}"
          >
            ×
          </button>
          <div
            class="modal fade"
            id="deletetip-{{ tip.id }}"
            tabindex="-1"
            role="dialog"
            aria-labelledby="deletetip-{{ tip.id }}Label"
            aria-hidden="true"
          >
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div
                  class="modal-header"
                  style="display: flex; flex-direction: row"
                >
                  <h5
                    class="modal-title inline"
                    style="width: 100%"
                    id="deletetip-{{ tip.id }}Label"
                  >
                    Delete Tip!
                  </h5>
                  <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-label="Close"
                  >
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form action="{% url 'tip' %}" method="post" class="form">
                  {% csrf_token %} {% bootstrap_form tip.deleteform %}
                  <div class="modal-footer">
                    {% buttons %}
                    <button type="submit" class="btn btn-primary">
                      {% bootstrap_icon "star" %} Ok
                    </button>
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-dismiss="modal"
                    >
                      Cancle
                    </button>
                    {% endbuttons %}
                  </div>
                </form>
              </div>
            </div>
          </div>
          {% endif %} {{ tip.author }}
        </h5>
        <p>{{ tip.content }}</p>
        <p>
          <small>{{ tip.date }}</small>
          <span onclick="document.getElementById('{{tip.id}}-upvote').click()"
            >👍{{tip.up_votes.count}}</span
          >
          -
          <span onclick="document.getElementById('{{tip.id}}-downvote').click()"
            >👎{{tip.down_votes.count}}</span
          >
        </p>
      </div>
    </li>
    {% endfor %}
  </ul>
  <div>{% endblock content %}</div>
</div>

rush01_Nginx/ex/templates/login.html
{% extends './base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block title %}
    Log in with {{ request.session.anonymous }}! | by spark.
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
   <div class="container py-5">
  <h1>Login</h1>
 <form action="{% url 'login' %}" method="post" class="form">
    {% csrf_token %}
   {% bootstrap_form form %}
    {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>
{% endblock %}

rush01_Nginx/ex/templates/mainpage.html
{% extends './base.html' %}
{% load static %}
{% block title %}
    Life Pro's Tip is {{ request.session.anonymous }}! | by spark.
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
  {% if Text != None %}
    <p style="font-size: 50px; color: ivory;">hmmm.. <br> {{Text}}! <br/> before, dink some {{ request.session.anonymous }} first.. <br> Enjoy!</p>
  {% else %}
    <p style="font-size: 50px; color: ivory;">Hello! Your Drink is <br >{{ request.session.anonymous }} ! <br> Enjoy!</p>
  {% endif %}
{% endblock %}

rush01_Nginx/ex/templates/nav.html
{% load static %}
{% load bootstrap3 %}
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="container-fluid">
      <div class="navbar-header">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'publication' %}">Hello! &nbsp;Awesome Cadet &nbsp;[ {{user.username}} ]!&nbsp;&nbsp; <br/> Your Black-hole is&nbsp;42&nbsp;Left..!</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'login' %}">Intranet For </br>Awesome Cadet!</a>
        {% endif %}
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li><a href="{% url 'profile' %}"> edit Profile </a></li>
          {% endif %}
          {% if user.is_superuser %}
          <li><a href="{% url 'admin' %}"> edit administrations </a></li>
          {% endif %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
              aria-expanded="false">
              {% if user.is_authenticated %}
              Hello! Awesome </br> {{ user.username }}!
              {% else %}
              No Log In? </br>Drinks Some {{ user.username }}...!
              {% endif %}
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}">Logout</a></li>
              <li><a href="{% url 'publish' %}">publish</a></li>
              <li><a href="{% url 'publication' %}">Home</a></li>
              {% else %}
              <li><a href="{% url 'register' %}">Register</a></li>
              <li><a href="{% url 'login' %}">Login</a></li>
              {% endif %}
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </div>
</nav>
{% comment %}
<nav class="navbar navbar-default navbar-fixed-bottom">
  <table>
    <td>
      <a href="http://localhost:8000/"> {{ request.session.anonymous }} is<br />
        <p style="font-size:40px">Life Pro Tip!</p>
      </a>
    </td>
    <td></td>
    <td></td>
    <td></td>
    <td><a href="http://localhost:8000/register">
        <p style="font-size:30px">Want <br /> Registration?</p>
      </a></td>
  </table>
</nav> {% endcomment %}

rush01_Nginx/ex/templates/post_detail.html
{% extends 'base.html' %} {% load bootstrap3 %} {% block title %}{{ object.title
}} | {% endblock title %} {% block content %}
<div>
  <h4 style="display: inline-block;">[{{ object.title }}]&nbsp;&nbsp;&nbsp;  </h4>
  <h5 style="display: inline-block;">{{ object.author }}
  </h5>
  <h6 style="display: inline-block;">- {{ object.created }}</h6>
  {% if user.is_authenticated %}
  {% endif %}
  <div class="lead">
    <div>{{ object.content }}</div>
    {% comment %} {% for c in comments%}
    {% endfor %} {% endcomment %}
  </div>
</div>



<form method="post" action="{% url 'create_comment' comments.id %}">
  {%csrf_token%}
  {{comment_form}}
  <input type="submit">
</form>
{% for i in object.comment_set.all %}





{% comment %} <p style="font-size:10px">->{{i}} &nbsp;&nbsp;&nbsp;&nbsp;_&nbsp;&nbsp;&nbsp;&nbsp;
  [{{i.created_at}}__by__{{i.author}}]</br></p> {% endcomment %}


<div class="media">
  <p class="pull-right"><small> {{i.created_at}}</small></p>
  <a class="media-left" href="#">
    <img src={{i.author.profile.image.url}} height=50>
  </a>
  <div class="media-body">
    <h5 class="media-heading user_name">{{i.author}}</h5>
    {{i.body}}
    <p><small><a href="">Like</a> - <a href="">Share</a></small></p>
  </div>
</div>

<form method="post" action="{% url 'create_recomment' comments.id %}">
    {%csrf_token%}
    {%for recom_form in recomment_form%}
        {%if recom_form.label != 'Comment' %}
        {{recom_form.label}} : {{recom_form}}
        {%endif%}
    {%endfor%}
    <input type="hidden" name="comment" value={{i.id}}>
    <input type="submit">
</form>
{%for recom in i.recomment_set.all%} &nbsp;&nbsp; &nbsp;&nbsp;
&nbsp;&nbsp;↪ &nbsp;{{recom}}  &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;[{{recom.created_at}}__by__{{recom.author}}]</br>
{%endfor%}
<hr>




{% comment %} <h6 style="font-size=10px">
  &nbsp; {{i.created_at}} &nbsp; by &nbsp;&nbsp;{{i.author}}</h6> {% endcomment %}

{% comment %} <form method="post" action="{% url 'create_comment' comments.id %}">
  {%csrf_token%}
  {{comment_form}}
  <input type="submit">
</form> {% endcomment %}

{% comment %} <h6 style="font-size=10px">{{i.author}}</h6> {% endcomment %}
{%endfor%}
{% endblock %}

rush01_Nginx/ex/templates/profile.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block content %}
    <h1 class="text-center">Change user Info</h1>
    <form method="POST" enctype="multipart/form-data">
    <!-- 파일을 업로드할 때 form method는 POST여야하고 enctype을 multipart/form-data로 설정해야 한다. -->
        {% csrf_token %}
        {% bootstrap_form user_change_form %}
        {% bootstrap_form profile_form %}
        <button type="submit" class="btn btn-primary">수정</button>
    </form>
{% endblock %}

rush01_Nginx/ex/templates/publish.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Publish | {% endblock %}

{% block content %}
<div>
    <h1>Publish</h1>
    <form action="{% url 'publish' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
    </form>
</div>
{% endblock content %}